config/routes.rb
ItnotesBack::Application.routes.draw do

  # MAIN PAGE
    root :to => 'welcome#shop'
  #END

  # USERS
    devise_for :users, :controllers => {:registrations => "users/registrations"} 
    namespace :users do
      resources :accounts 
      resources :composers, :only => [:new, :show, :create, :destroy]
      resources :notifications, :except => [:edit, :update]
      resources :wishes
    end
  # END

  # ALBUMS AND COMPOSITIONS
    namespace :items do
      resources :compilations do
        member do
          post '/add' => 'compilations#add_albums', as: 'add'
        end
      end
      resources :albums do
        member do
          post '/send' => 'albums#send_to_compilation', as: 'send'
          post '/add' => 'albums#add_compositions', as: 'add'
        end
      end
      resources :compositions do
        member do 
          post '/send' => 'compositions#send_to_album', as: 'send'
        end
      end
      resources :groups
      # INIT PAYMENT
        post "/payments/create" => "payments#create"
      # PAID - ROBOKASSA
        get "/payments/success" => "payments#success"
        get "/payments/fail" => "payments#fail"
      # END
    end
    # WORK WITH SHOP
      get "/sale/:item/:id" => "sales#new", as: 'sale'
      post "/sale/send/:item/:id" => "sales#create", as: 'send_sale'
      post "/sale/pause/:item/:id" => "sales#pause", as: 'pause_sale'
      post "/sale/play/:item/:id" => "sales#play", as: 'play_sale'
    # END
  # END

  # INFORMATION
    resources :feedbacks
  # END

  # DOWNLOAD
    post '/composition/:id' => 'download#composition', as: 'download_composition'
  # END

  # HELP
    get '/help/create_composition' => 'help#create_composition', as: 'create_composition_help'
    get '/help/create_album' => 'help#create_album', as: 'create_album_help'
    get '/help/create_compilation' => 'help#create_compilation', as: 'create_compilation_help'
    get '/help/sale_all' => 'help#sale_all', as: 'sale_all_help'
  # END
  
  # SEARCH
    get '/:category/:item' => 'search#show', as: 'show_category'
  # END

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_one :account
  has_one :cart
  has_one :library
  has_many :notifications
  has_many :wishes

  include Models::ItemsMethods::HistoryMethods
  
  after_create :add_instruments

  private

  	def add_instruments
      self.create_cart
      self.create_library
  	end
  	
end

app/models/wish.rb
class Wish < ActiveRecord::Base
  attr_accessible :author, :genre, :instrument, :user_id, :w_name, :finded, :comment

  belongs_to :user

  validates :author, :presence => true
  validates :genre, :presence => true
  validates :instrument, :presence => true
  validates :w_name, :presence => true
  validates :comment, :presence => true

  include Models::ItemsMethods::HistoryMethods
  
end

app/controllers/users/accounts_controller.rb
# encoding: utf-8
class Users::AccountsController < ApplicationController

	before_filter :authenticate_user!

	def new
		@account = Account.new
		@url = "users/accounts"
	end

	def create
		@account = current_user.create_account(params[:account])
		if @account.save
			#TODO: Отправка письма с подтверждением регистрации
			#TODO: Создание сообщение с приветствием
			redirect_to users_account_path(@account)
		else
			render :new
		end
	end

	def edit
		@account = current_user.account
		@url = "users/account"
	end

	def update
		if current_user.account.update_attributes(params[:account])
			redirect_to shop_path
		else
			render :edit
		end
	end

end

app/controllers/users/composers_controller.rb
#encoding: utf-8
class Users::ComposersController < ApplicationController

  before_filter :composer_validate, :except => [:new, :create]

  def new
  	@position = "Принятие соглашения"
  end

  def create
  	current_user.account.update_attributes(composer: true, acepted: true)
  	redirect_to action: :show, id: current_user, type: "all"
  end

  def show
  	if current_user.account.composer?
	  	case params[:type]
	  		when "all"
	  			@position = "Моя витрина | Все"
	  			@compilations = Compilation.where(composer_id: current_user)
	  			@albums = Album.where(composer_id: current_user, compilation_id: 0)
	  			@compositions = Composition.where(composer_id: current_user, album_id: 0)
	  		when "sale"
	  			@position = "Моя витрина | В продаже"
	  			@compilations = Compilation.where(composer_id: current_user, active: true)
	  			@albums = Album.where(composer_id: current_user, active: true, compilation_id: 0)
	  			@compositions = Composition.where(composer_id: current_user, active: true, album_id: 0)
	  		when "wait"
	  			@position = "Моя витрина | Ожидают продажи"
	  			@compilations = Compilation.where(composer_id: current_user, active: false)
	  			@albums = Album.where(composer_id: current_user, active: false, compilation_id: 0)
	  			@compositions = Composition.where(composer_id: current_user, active: false, album_id: 0)
	  	end
    else
      redirect_to :back
    end
  end

end

app/controllers/users/notifications_controller.rb
#encoding: utf-8
class Users::NotificationsController < ApplicationController

	before_filter :authenticate_user!

	def index
		@position = "Мои сообщения"
		@notifys = current_user.notifications
	end

	def show
		@position = "Просмотр сообщения"
		@notify = current_user.notifications.find(params[:id])
		@notify.toggle!(:viewed) if !@notify.viewed?
	end

	def destroy
		current_user.notifications.find(params[:id]).delete
		redirect_to action: :index
	end
	
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	
	protected

		def after_sign_up_path_for(resource)
  			new_users_account_path
  		end
	
end

app/controllers/users/wishes_controller.rb
# encoding: utf-8
class Users::WishesController < ApplicationController

	before_filter :authenticate_user!

  def index
    @position = "Мои пожелания"
  	@wishes = current_user.wishes
  end

  def show
  end

  def new
    @position = "Новое пожелание"
  	@wish = Wish.new
  end

  def create
  	@wish = Wish.create(params[:wish])
  	if @wish.save
  		current_user.wishes << @wish
  		redirect_to action: :index
  	else 
  		render 'new'
  	end
  end

  def destroy
  	current_user.wishes.find(params[:id]).delete
  	redirect_to action: :index
  end
end

app/helpers/users/composers_helper.rb
#encoding: utf-8
module Users::ComposersHelper

end

app/views/users/wishes/index.html.haml
= render "layouts/head_bar"
.row-fluid.all-controls
	.span2
		= render "layouts/nav"
	.span10
		.wishes
			.alert.alert-info
				Здесь вы можете добавлять в список свои пожелания относительно наличия композиций в магазине, те которые вы хотели бы приобрести или получить бесплатно. Мы их обязательно найдем и сообщим вам. 
			%table.table
				%tbody
					- @wishes.each do |wish|
						- if wish.finded?
							%tr{style: "background: #D9EDF7;"}
								%td= wish.w_name
								%td= wish.author
								%td= wish.instrument
								%td= wish.genre
								%td= link_to image_tag("delete.png"), users_wish_path(wish), method: :delete, class: "btn btn-danger btn-mini",confirm: "Вы уверены, что хотите удалить это пожелание?", title: "Удалить пожелание"
						- else
							%tr
								%td= wish.w_name
								%td= wish.author
								%td= wish.instrument
								%td= wish.genre
								%td= link_to image_tag("delete.png"), users_wish_path(wish), method: :delete, class: "btn btn-danger btn-mini",confirm: "Вы уверены, что хотите удалить это пожелание?", title: "Удалить пожелание"
			.add-wish
				%a.btn.btn-info.btn-large{href: "/users/wishes/new"} Добавить пожелание

app/views/users/wishes/new.html.haml
= render "layouts/head_bar"
.row-fluid.all-controls
	.span2
		= render "layouts/nav"
	.span10
		.wishes.new
			%h2 Добавление пожелания
			= form_for @wish, :url => users_wishes_path,:html => {:class => "form-horizontal"} do |f|
				.control-group
					= f.label 'Название', class: "control-label"
					.controls
						= f.text_field :w_name
						%span.help-inline композиции или альбома
				.control-group
					= f.label 'Автор', class: "control-label"
					.controls
						= f.text_field :author
				.control-group
					= f.label 'Инструмент', class: "control-label"
					.controls
						= f.text_field :instrument
				.control-group
					= f.label 'Жанр', class: "control-label"
					.controls
						= f.text_field :genre
				.control-group
					= f.label 'Коментарий', class: "control-label"
					.controls
						= f.text_area :comment
				.control-group
					.controls
						= f.submit 'Добавить', class: "btn btn-info btn-large"