config/routes.rb
ItnotesBack::Application.routes.draw do

  # MAIN PAGE
    root :to => 'welcome#shop'
  #END

  # USERS
    devise_for :users, :controllers => {:registrations => "users/registrations"} 
    namespace :users do
      resources :accounts 
      resources :composers, :only => [:new, :show, :create, :destroy]
      resources :notifications, :except => [:edit, :update]
      resources :wishes
    end
  # END

  # ALBUMS AND COMPOSITIONS
    namespace :items do
      resources :compilations do
        member do
          post '/add' => 'compilations#add_albums', as: 'add'
        end
      end
      resources :albums do
        member do
          post '/send' => 'albums#send_to_compilation', as: 'send'
          post '/add' => 'albums#add_compositions', as: 'add'
        end
      end
      resources :compositions do
        member do 
          post '/send' => 'compositions#send_to_album', as: 'send'
        end
      end
      resources :groups
      # INIT PAYMENT
        post "/payments/create" => "payments#create"
      # PAID - ROBOKASSA
        get "/payments/success" => "payments#success"
        get "/payments/fail" => "payments#fail"
      # END
    end
    # WORK WITH SHOP
      get "/sale/:item/:id" => "sales#new", as: 'sale'
      post "/sale/send/:item/:id" => "sales#create", as: 'send_sale'
      post "/sale/pause/:item/:id" => "sales#pause", as: 'pause_sale'
      post "/sale/play/:item/:id" => "sales#play", as: 'play_sale'
    # END
  # END

  # INFORMATION
    resources :feedbacks
  # END

  # DOWNLOAD
    post '/composition/:id' => 'download#composition', as: 'download_composition'
  # END

  # HELP
    get '/help/create_composition' => 'help#create_composition', as: 'create_composition_help'
    get '/help/create_album' => 'help#create_album', as: 'create_album_help'
    get '/help/create_compilation' => 'help#create_compilation', as: 'create_compilation_help'
    get '/help/sale_all' => 'help#sale_all', as: 'sale_all_help'
  # END
  
  # SEARCH
    get '/:category/:item' => 'search#show', as: 'show_category'
  # END

end

app/controllers/search_controller.rb
# encoding: utf-8
class SearchController < ApplicationController

	def show
		@composers = Composition.sale.where("author IS NOT NULL").select(:author).group(:author).limit(15)
    	@instruments = Composition.sale.where("instrument IS NOT NULL").select(:instrument).group(:instrument).limit(15)
    	@genres = Composition.sale.where("genre IS NOT NULL").select(:genre).group(:genre).limit(15)
		if user_signed_in?
	      @page_size = "span10"
	    else
	      @page_size = "span12"
	    end	
	    @position = params[:category]
	    @item = params[:item]
	    @view = "album"
	    case params[:category]
	    	when "Жанры"
	    		@compositions = Composition.sale.where(genre: params[:item]).order("b_count DESC")
	    		@albums = Album.sale.where(genre: params[:item]).order("b_count DESC")
	    		@compilations = Compilation.sale.where(genre: params[:item]).order("b_count DESC")
	    		@view = "all"
	    	when "Инструменты"
	    		@compositions = Composition.sale.where(instrument: params[:item]).order("b_count DESC")
	    		@view = "composition"
	    	when "Композиторы"
	    		@compositions = Composition.sale.where(author: params[:item]).order("b_count DESC")
	    		@albums = Album.sale.where(author: params[:item]).order("b_count DESC")
	    		@compilations = Compilation.sale.where(author: params[:item]).order("b_count DESC")
	    		@view = "all"
	    	when "Коллекции"
	    		@view = "compilation"
	    		@items = Compilation.sale.order("created_at DESC")
	    	when "Лучшие сборники"
	    		@items = Album.sale.order("b_count DESC")
	    	when "Новые сборники"
	    		@items = Album.sale.order("created_at DESC")
	    	when "Популярные композиции"
	    		#TODO: Просмотр всех композиций
	    		@view = "composition"
	    	when "Все"
	    		@item = "Результаты по запросу: " + params[:search]
	    		@view = "all"
	    		@albums = ThinkingSphinx.search(params[:search], :classes => [Album], :with => {:active => '1', :paused => '0'})
	    		@compilations = ThinkingSphinx.search(params[:search], :classes => [Compilation], :with => {:active => '1', :paused => '0'})
	    		@compositions = ThinkingSphinx.search(params[:search], :classes => [Composition], :with => {:active => '1', :paused => '0'})
	    end
	    	
	end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/show.html.haml
%article.container-fluid.shop
	= render "layouts/head_bar"
	.row-fluid.all-controls
		- if user_signed_in?
			.span2
				= render "layouts/nav"
		%div{class: @page_size}
			= render "layouts/search"
			.row-fluid
				.span10.best
					.section.items
						.page-header
							%h2 
								= @item
						- if @view == "composition"
							.section
								.compositions
									%table.table.table-hover
										%thead
											%tr
												%th #
												%th Название
												%th Альбом
												%th Композитор 
												%th Жанр
												%th Инструмент
												%th
										%tbody
											- number = 1
											- @compositions.each do |composition|
												%tr
													%td= number
													%td= link_to composition.c_name, items_composition_path(composition)
													- if composition.album.nil?
														%td 
															\-
													- else
														%td{title: composition.album.a_name}
															= link_to truncate(composition.album.a_name, length: 20), items_album_path(composition.album)
													%td= link_to composition.author, show_category_path("Композиторы", composition.author)
													- if composition.genre != ""
														%td= link_to composition.genre, show_category_path("Жанры", composition.genre)
													- else 
														%td= link_to composition.album.genre, show_category_path("Жанры", composition.album.genre)
													%td= link_to composition.instrument, show_category_path("Инструменты", composition.instrument)
													%td
														- if composition.preferences[:audio] != "null"
															.player{id: "audio-#{composition.id}"}
															%a.icon-bullhorn{href:"#", id:"play-#{composition.id}", onclick: "soundManager.setup({ url: '/', onready: function (){ soundManager.createSound({ id: \"audio-#{composition.id}\", url: \"/assets/audio/#{composition.preferences[:audio]}\", autoLoad: false, autoPlay: false, volume: 50}); soundManager.play(\"audio-#{composition.id}\");} }); $(this).hide(); $(\"#pause-#{composition.id}\").show();" }
															%a.icon-pause{href:"#", style:"display: none;", id:"pause-#{composition.id}", onclick:"soundManager.stop(\"audio-#{composition.id}\"); $(this).hide(); $(\"#play-#{composition.id}\").show();" }
												- number += 1
						- if @view == "album"
							.albums
								- @items.each do |album|
									%a{:href => "/items/albums/#{album.id}"}
										.album
											= image_tag("/assets/covers/#{album.cover}", size: "80x80", class: "thumbnail")
											%span.album-name{:title => album.a_name}= truncate(album.a_name, length: 17)
											%br
											%span.author{:title => album.author}= album.short_composer
											%br
											%span.genre= truncate(album.genre, length: 17)
						- if @view == "compilation"
							.albums
								- @items.each do |compilation|
									%a{:href => "/items/compilations/#{compilation.id}"}
										.compilation
											%span.compilation-cover-mini.thumbnail
												- compilation.albums.limit(4).each do |album|
													= image_tag("/assets/covers/#{album.cover}", size: "60x60")
											%span.album-name{:title => compilation.c_name}= truncate(compilation.c_name, length: 30)
											%br
											%span.author{:title => compilation.author}= compilation.short_composer
						- if @view == "all"
							- if @compilations.any?
								.section
									.page-header
										%h3 Коллекции
									.albums
										- @compilations.each do |compilation|
											%a{:href => "/items/compilations/#{compilation.id}"}
												.compilation
													%span.compilation-cover-mini.thumbnail
														- compilation.albums.limit(4).each do |album|
															= image_tag("/assets/covers/#{album.cover}", size: "60x60")
													%span.album-name{:title => compilation.c_name}= truncate(compilation.c_name, length: 30)
													%br
													%span.author{:title => compilation.author}= compilation.short_composer
							- if @albums.any?
								.section
									.page-header
										%h3 Сборники
									.albums
										- @albums.each do |album|
											%a{:href => "/items/albums/#{album.id}"}
												.album
													= image_tag("/assets/covers/#{album.cover}", size: "80x80", class: "thumbnail")
													%span.album-name{:title => album.a_name}= truncate(album.a_name, length: 17)
													%br
													%span.author{:title => album.author}= album.short_composer
													%br
													%span.genre= truncate(album.genre, length: 17)
							- if @compositions.any?
								.section
									.page-header
										%h3 Композиции
									.compositions
										%table.table.table-hover
											%thead
												%tr
													%th #
													%th Название
													%th Альбом
													%th Композитор 
													%th Жанр
													%th Инструмент
													%th
											%tbody
												- number = 1
												- @compositions.each do |composition|
													%tr
														%td= number
														%td= link_to composition.c_name, items_composition_path(composition)
														- if composition.album.nil?
															%td 
																\-
														- else
															%td{title: composition.album.a_name}
																= link_to truncate(composition.album.a_name, length: 20), items_album_path(composition.album)
														%td= link_to composition.author, show_category_path("Композиторы", composition.author)
														- if composition.genre != ""
															%td= link_to composition.genre, show_category_path("Жанры", composition.genre)
														- else 
															%td= link_to composition.album.genre, show_category_path("Жанры", composition.album.genre)
														%td= link_to composition.instrument, show_category_path("Инструменты", composition.instrument)
														%td
															- if composition.preferences[:audio] != "null"
																.player{id: "audio-#{composition.id}"}
																%a.icon-bullhorn{href:"#", id:"play-#{composition.id}", onclick: "soundManager.setup({ url: '/', onready: function (){ soundManager.createSound({ id: \"audio-#{composition.id}\", url: \"/assets/audio/#{composition.preferences[:audio]}\", autoLoad: false, autoPlay: false, volume: 50}); soundManager.play(\"audio-#{composition.id}\");} }); $(this).hide(); $(\"#pause-#{composition.id}\").show();" }
																%a.icon-pause{href:"#", style:"display: none;", id:"pause-#{composition.id}", onclick:"soundManager.stop(\"audio-#{composition.id}\"); $(this).hide(); $(\"#play-#{composition.id}\").show();" }
													- number += 1
				.span2.sidebar
					.section.genres
						%h6 Жанры
						%ul
							- @genres.each do |g|
								%li= link_to g.genre, show_category_path("Жанры", g.genre)
					.section.instruments
						%h6 Инструменты
						%ul 
							- @instruments.each do |i|
								%li= link_to i.instrument, show_category_path("Инструменты", i.instrument)
					.section.compositors
						%h6 Композиторы
						%ul
							- @composers.each do |composer|
								%li= link_to composer.short_composer, show_category_path("Композиторы", composer.author)