config/routes.rb
ItnotesBack::Application.routes.draw do

  # MAIN PAGE
    root :to => 'welcome#shop'
  #END

  # USERS
    devise_for :users, :controllers => {:registrations => "users/registrations"} 
    namespace :users do
      resources :accounts 
      resources :composers, :only => [:new, :show, :create, :destroy]
      resources :notifications, :except => [:edit, :update]
      resources :wishes
    end
  # END

  # ALBUMS AND COMPOSITIONS
    namespace :items do
      resources :compilations do
        member do
          post '/add' => 'compilations#add_albums', as: 'add'
        end
      end
      resources :albums do
        member do
          post '/send' => 'albums#send_to_compilation', as: 'send'
          post '/add' => 'albums#add_compositions', as: 'add'
        end
      end
      resources :compositions do
        member do 
          post '/send' => 'compositions#send_to_album', as: 'send'
        end
      end
      resources :groups
      # INIT PAYMENT
        post "/payments/create" => "payments#create"
      # PAID - ROBOKASSA
        get "/payments/success" => "payments#success"
        get "/payments/fail" => "payments#fail"
      # END
    end
    # WORK WITH SHOP
      get "/sale/:item/:id" => "sales#new", as: 'sale'
      post "/sale/send/:item/:id" => "sales#create", as: 'send_sale'
      post "/sale/pause/:item/:id" => "sales#pause", as: 'pause_sale'
      post "/sale/play/:item/:id" => "sales#play", as: 'play_sale'
    # END
  # END

  # INFORMATION
    resources :feedbacks
  # END

  # DOWNLOAD
    post '/composition/:id' => 'download#composition', as: 'download_composition'
  # END

  # HELP
    get '/help/create_composition' => 'help#create_composition', as: 'create_composition_help'
    get '/help/create_album' => 'help#create_album', as: 'create_album_help'
    get '/help/create_compilation' => 'help#create_compilation', as: 'create_compilation_help'
    get '/help/sale_all' => 'help#sale_all', as: 'sale_all_help'
  # END
  
  # SEARCH
    get '/:category/:item' => 'search#show', as: 'show_category'
  # END

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_one :account
  has_one :cart
  has_one :library
  has_many :notifications
  has_many :wishes

  include Models::ItemsMethods::HistoryMethods
  
  after_create :add_instruments

  private

  	def add_instruments
      self.create_cart
      self.create_library
  	end
  	
end

app/controllers/users/accounts_controller.rb
# encoding: utf-8
class Users::AccountsController < ApplicationController

	before_filter :authenticate_user!

	def new
		@account = Account.new
		@url = "users/accounts"
	end

	def create
		@account = current_user.create_account(params[:account])
		if @account.save
			#TODO: Отправка письма с подтверждением регистрации
			#TODO: Создание сообщение с приветствием
			redirect_to users_account_path(@account)
		else
			render :new
		end
	end

	def edit
		@account = current_user.account
		@url = "users/account"
	end

	def update
		if current_user.account.update_attributes(params[:account])
			redirect_to shop_path
		else
			render :edit
		end
	end

end

app/controllers/users/composers_controller.rb
#encoding: utf-8
class Users::ComposersController < ApplicationController

  before_filter :composer_validate, :except => [:new, :create]

  def new
  	@position = "Принятие соглашения"
  end

  def create
  	current_user.account.update_attributes(composer: true, acepted: true)
  	redirect_to action: :show, id: current_user, type: "all"
  end

  def show
  	if current_user.account.composer?
	  	case params[:type]
	  		when "all"
	  			@position = "Моя витрина | Все"
	  			@compilations = Compilation.where(composer_id: current_user)
	  			@albums = Album.where(composer_id: current_user, compilation_id: 0)
	  			@compositions = Composition.where(composer_id: current_user, album_id: 0)
	  		when "sale"
	  			@position = "Моя витрина | В продаже"
	  			@compilations = Compilation.where(composer_id: current_user, active: true)
	  			@albums = Album.where(composer_id: current_user, active: true, compilation_id: 0)
	  			@compositions = Composition.where(composer_id: current_user, active: true, album_id: 0)
	  		when "wait"
	  			@position = "Моя витрина | Ожидают продажи"
	  			@compilations = Compilation.where(composer_id: current_user, active: false)
	  			@albums = Album.where(composer_id: current_user, active: false, compilation_id: 0)
	  			@compositions = Composition.where(composer_id: current_user, active: false, album_id: 0)
	  	end
    else
      redirect_to :back
    end
  end

end

app/controllers/users/notifications_controller.rb
#encoding: utf-8
class Users::NotificationsController < ApplicationController

	before_filter :authenticate_user!

	def index
		@position = "Мои сообщения"
		@notifys = current_user.notifications
	end

	def show
		@position = "Просмотр сообщения"
		@notify = current_user.notifications.find(params[:id])
		@notify.toggle!(:viewed) if !@notify.viewed?
	end

	def destroy
		current_user.notifications.find(params[:id]).delete
		redirect_to action: :index
	end
	
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	
	protected

		def after_sign_up_path_for(resource)
  			new_users_account_path
  		end
	
end

app/controllers/users/wishes_controller.rb
# encoding: utf-8
class Users::WishesController < ApplicationController

	before_filter :authenticate_user!

  def index
    @position = "Мои пожелания"
  	@wishes = current_user.wishes
  end

  def show
  end

  def new
    @position = "Новое пожелание"
  	@wish = Wish.new
  end

  def create
  	@wish = Wish.create(params[:wish])
  	if @wish.save
  		current_user.wishes << @wish
  		redirect_to action: :index
  	else 
  		render 'new'
  	end
  end

  def destroy
  	current_user.wishes.find(params[:id]).delete
  	redirect_to action: :index
  end
end

app/helpers/users/composers_helper.rb
#encoding: utf-8
module Users::ComposersHelper

end

app/views/users/composers/_add_compositions_to_album.haml
%a.icon-upload{href: "#add-compositions-#{album.id}", title: "Добавить композиции в сборник"}(data-toggle="modal")
.modal.hide.fade{id: "add-compositions-#{album.id}"}
    .modal-header
        %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        %h3 Добавление композиций в сборник
    .modal-body{style: "height: 200px;"}
        = form_for :upload, url: add_items_album_path(album) do |f|
            = f.hidden_field :where, value: params[:type]
            = f.label 'Выберите композиции'
            %br
            = compositions_select
            %br
            %br
            %br
            %br
            %br
            = f.submit 'Добавить', class: "btn btn-success"
    - script = "$(\"#add-compositions-#{album.id}\").modal('toggle');"
    %script= script

app/views/users/composers/_album_controls.haml
= link_to "", edit_items_album_path(album), class: "icon-edit", title: "Редактировать"
- unless album.active?
    = link_to "", sale_path('album', album), class: "icon-shopping-cart", title: "Продать"
    = link_to "", {controller: "items/albums", action: :destroy, id: album, from: "all"}, class: "icon-trash", method: :delete, confirm: "Вы точно хотите удалить альбом \"#{album.a_name}\"?", title: "Удалить"
- if !album.paused? && album.active?
    = link_to "", pause_sale_path('album', album), class: "icon-minus-sign", title: "Приостановить продажу", method: :post, confirm: "Вы уверены, что хотите приостановить продажу?"
- if album.paused?
    = link_to "", play_sale_path('album', album), class: "icon-plus-sign", title: "Вернуть в продажу", method: :post, confirm: "Вы уверены, что хотите вернуть в продажу?"
= render "move_album_to_compilation", album: album
= render "add_compositions_to_album", album: album

app/views/users/composers/_albums.haml
.page-header
    %h2
        Сборники
        %small= link_to "Добавить", new_items_album_path

- if @albums.any?
    .albums
        - @albums.each do |album|
            %a{href: "/items/albums/#{album.id}"}
                .album
                    = item_badge(album)
                    = image_tag(album.cover, size: "80x80", class: "thumbnail")
                    %span.album-name{title: album.a_name}= truncate(album.a_name, length: 50)
                    %br
                    %span.author{title: album.author}= album.short_composer
                    %br
                    %span.genre= album_genre(album)
                .controls= render "album_controls", album: album
- else
    %i Пока ничего нет

app/views/users/composers/_compilations.haml
.page-header
    %h2
        Коллекции
        %small= link_to "Добавить", new_items_compilation_path
- if @compilations.any?
    .albums
        - @compilations.each do |compilation|
            %a{:href => "/items/compilations/#{compilation.id}"}
                .compilation
                    - if !compilation.active?
                        %span.label.label-important Wait
                    - if compilation.active?
                        %span.label.label-success Sale
                    - if compilation.active? && compilation.paused?
                        %span.label.label-info Paused
                    %span.compilation-cover-mini.thumbnail
                        - compilation.albums.limit(4).each do |album|
                            = image_tag("/assets/covers/#{album.cover}", size: "60x60")
                    %span.album-name{:title => compilation.c_name}= truncate(compilation.c_name, length: 30)
                .controls
                    = #link_to "", '#', class: "icon-edit", title: "Редактировать"
                    - if !compilation.active?
                        = link_to "", sale_path('compilation', compilation), class: "icon-shopping-cart", title: "Продать"
                        = link_to "", {controller: "items/compilations", action: :destroy, id: compilation, from: "all"}, class: "icon-trash", method: :delete, confirm: "Вы точно хотите удалить коллекцию \"#{compilation.c_name}\"?", title: "Удалить"
                    - if !compilation.paused? && compilation.active?
                        = link_to "", pause_sale_path('compilation', compilation), class: "icon-minus-sign", title: "Приостановить продажу", method: :post, confirm: "Вы уверены, что хотите приостановить продажу?"
                    - if compilation.paused?
                        = link_to "", play_sale_path('compilation', compilation), class: "icon-plus-sign", title: "Вернуть в продажу", method: :post, confirm: "Вы уверены, что хотите вернуть в продажу?"
                    %a.icon-upload{href: "#add-albums-#{compilation.id}", title: "Добавить сборники в коллекцию"}(data-toggle="modal")
                    .modal.hide.fade{id: "add-albums-#{compilation.id}"}
                        .modal-header
                            %button.close(type="button" data-dismiss="modal" aria-hidden="true")
                                &times;
                            %h3 Добавление сборников в коллекцию
                        .modal-body{style: "height: 200px;"}
                            = form_for :upload, url: add_items_compilation_path(compilation) do |f|
                                = f.hidden_field :where, value: params[:type]
                                = f.label 'Выберите сборники'
                                %br
                                = select_tag :albums, options_from_collection_for_select(@all_albums, "id", "a_name"), placeholder: "Выберите сборники...", multiple: true, size: 10, class: "chzn-select"
                                %br
                                %br
                                %br
                                %br
                                %br
                                = f.submit 'Добавить', class: "btn btn-success"
                        - script = "$(\"#add-albums-#{compilation.id}\").modal('toggle');"
                        %script= script
- else
    %i Пока ничего нет

app/views/users/composers/_compositions.haml
.page-header
    %h2
        Композиции
        %small= link_to "Добавить", new_items_composition_path

- if @compositions.any? && !@compositions.nil?
    %table.table.table-hover
        %thead
            %tr
                %th #
                %th Название
                %th Альбом
                %th Композитор
                %th Жанр
                %th Инструмент
                %th
        %tbody
            - @compositions.order("created_at ASC").each_with_index do |composition, row_number|
                %tr
                    %td= row_number + 1
                    %td
                        = link_to composition.c_name, items_composition_path(composition)
                        = item_badge(composition)
                    %td= composition_album(composition)
                    %td= composition.author
                    %td= composition_genre(composition)
                    %td= composition.instrument
                    %td
                        = render "layouts/player_for", composition: composition
                        = render "compositions_controls", composition: composition
                        = render "move_composition_to_album", composition: composition
- else
    %i Пока ничего нет

app/views/users/composers/_compositions_controls.haml
= link_to "", '#', class: "icon-edit", title: "Редактировать"
- unless composition.active?
    = link_to "", sale_path('composition', composition), class: "icon-shopping-cart", title: "Продать"
    = link_to "", {controller: "items/compositions", action: :destroy, id: composition, from: "all"}, class: "icon-trash", method: :delete, confirm: "Вы точно хотите удалить композицию \"#{composition.c_name}\"?", title: "Удалить"
- if !composition.paused? && composition.active?
    = link_to "", pause_sale_path('composition', composition), class: "icon-minus-sign", title: "Приостановить продажу", method: :post, confirm: "Вы уверены, что хотите приостановить продажу?"
- if composition.paused?
    = link_to "", play_sale_path('composition', composition), class: "icon-plus-sign", title: "Вернуть в продажу", method: :post, confirm: "Вы уверены, что хотите вернуть в продажу?"

app/views/users/composers/_move_album_to_compilation.haml
%a.icon-share{href: "#send-album-#{album.id}", title: "Переместить сборник в коллекцию"}(data-toggle="modal")
.modal.hide.fade{id: "send-album-#{album.id}"}
    .modal-header
        %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        %h3 Переместить сборник в коллекцию
    .modal-body
        = form_for :send, url: send_items_album_path(album) do |f|
            = f.hidden_field :where, value: params[:type]
            = f.label 'В коллекцию', class: "control-label"
            %br
            = compilations_select
            %br
            %br
            %br
            = f.submit 'Переместить', class: "btn btn-success"
    - script = "$(\"#send-album-#{album.id}\").modal('toggle');"
    %script= script

app/views/users/composers/_move_composition_to_album.haml
%a.icon-share{href: "#send-composition-#{composition.id}", title: "Переместить композицию в альбом"}(data-toggle="modal")
.modal.hide.fade{id: "send-composition-#{composition.id}"}
    .modal-header
        %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        %h3 Переместить композицию в сборник
    .modal-body
        = form_for :send, url: send_items_composition_path(composition) do |f|
            = f.hidden_field :where, value: params[:type]
            = f.label 'В сборник', class: "control-label"
            %br
            = albums_select
            %br
            %br
            %br
            = f.submit 'Переместить', class: "btn btn-success"
    - script = "$(\"#send-composition-#{composition.id}\").modal('toggle');"
    %script= script

app/views/users/composers/new.html.haml
= render "layouts/head_bar"
.row-fluid.all-controls
	.span2
		= render "layouts/nav"
	.span10
		.register.edit.composer
			.page-header
				%h2.edit-account 
					Начало продаж в магазине ITNotes
			.licence
				%h4 Прочтите и примите условия продаж в нашем магазине
				%p
					ВНИМАТЕЛЬНО ПРОЧИТАЙТЕ ЭТИ УСЛОВИЯ ИСПОЛЬЗОВАНИЯ, ПРЕЖДЕ ЧЕМ ПОЛЬЗОВАТЬСЯ УСЛУГАМИ, ПРЕДЛАГАЕМЫМИ СЕРВИСОМ ITNOTES, ЗАРЕГИСТРИРОВАННОМ В АРХАНГЕЛЬСКЕ. ЭТИ УСЛОВИЯ ИСПОЛЬЗОВАНИЯ СОДЕРЖАТ ЮРИДИЧЕСКИ ОБЯЗАТЕЛЬНЫЕ УСЛОВИЯ, КОТОРЫЕ ВЫ ДОЛЖНЫ СОБЛЮДАТЬ ПРИ ИСПОЛЬЗОВАНИИ ВЕБ-САЙТА 
					= link_to "HTTP://SHOP.ITNOT.ES/", root_path 
					("САЙТ") И УСЛУГ, ОПЦИЙ, КОНТЕНТА, ПРИЛОЖЕНИЙ ИЛИ ВИДЖЕТОВ, ПРЕДЛАГАЕМЫХ ITNOTES (ВМЕСТЕ С САЙТОМ В ДАЛЬНЕЙШЕМ ИМЕНУЕМЫЕ "СЕРВИС").
				%p 
					Здесь что-то надо написать. Про способы оплаты, про способы снятия денег со счета, процент с продаж. Ответственность и всякая такая ерунда.
			.accept
				= link_to "Отменить", :back, class: "btn"
				= link_to "Принять", {controller: "users/composers", action: "create"}, class: "btn btn-success", method: :post

app/views/users/composers/show.html.haml
%article.container-fluid.shop
	= render "layouts/head_bar"
	.row-fluid.all-controls
		.span2
			= render "layouts/nav"
		.span10
			= render "layouts/composer_help"
			.row-fluid
				.best.showcase
					.section= render "compilations"
					.section= render "albums"
					.section= render "compositions"