config/routes.rb
ItnotesBack::Application.routes.draw do

  # MAIN PAGE
    root :to => 'welcome#shop'
  #END

  # USERS
    devise_for :users, :controllers => {:registrations => "users/registrations"} 
    namespace :users do
      resources :accounts 
      resources :composers, :only => [:new, :show, :create, :destroy]
      resources :notifications, :except => [:edit, :update]
      resources :wishes
    end
  # END

  # ALBUMS AND COMPOSITIONS
    namespace :items do
      resources :compilations do
        member do
          post '/add' => 'compilations#add_albums', as: 'add'
        end
      end
      resources :albums do
        member do
          post '/send' => 'albums#send_to_compilation', as: 'send'
          post '/add' => 'albums#add_compositions', as: 'add'
        end
      end
      resources :compositions do
        member do 
          post '/send' => 'compositions#send_to_album', as: 'send'
        end
      end
      resources :groups
      # INIT PAYMENT
        post "/payments/create" => "payments#create"
      # PAID - ROBOKASSA
        get "/payments/success" => "payments#success"
        get "/payments/fail" => "payments#fail"
      # END
    end
    # WORK WITH SHOP
      get "/sale/:item/:id" => "sales#new", as: 'sale'
      post "/sale/send/:item/:id" => "sales#create", as: 'send_sale'
      post "/sale/pause/:item/:id" => "sales#pause", as: 'pause_sale'
      post "/sale/play/:item/:id" => "sales#play", as: 'play_sale'
    # END
  # END

  # INFORMATION
    resources :feedbacks
  # END

  # DOWNLOAD
    post '/composition/:id' => 'download#composition', as: 'download_composition'
  # END

  # HELP
    get '/help/create_composition' => 'help#create_composition', as: 'create_composition_help'
    get '/help/create_album' => 'help#create_album', as: 'create_album_help'
    get '/help/create_compilation' => 'help#create_compilation', as: 'create_compilation_help'
    get '/help/sale_all' => 'help#sale_all', as: 'sale_all_help'
  # END
  
  # SEARCH
    get '/:category/:item' => 'search#show', as: 'show_category'
  # END

end

app/models/compilation.rb
class Compilation < ActiveRecord::Base
  attr_accessible :active, :author, :c_name, :description, :genre, :sale, :cost, :composer_id, :group_id, 
                  :preferences, :paused, :locked

  has_many :albums
  belongs_to :group
  
  include Models::ItemsMethods::HistoryMethods
  include Models::ItemsMethods
  include Models::ItemsMethods::InstanceMethods

  def recost
    cost = 0
    self.albums.each do |a|
      album_cost = 0
      a.compositions.each do |c|
        album_cost += c.cost
      end
      a.update_attributes(cost: album_cost)
      cost += album_cost
    end
    self.update_attributes(cost: cost)
  end
end

app/controllers/items/albums_controller.rb
#encoding: utf-8
class Items::AlbumsController < Items::ItemsController

	before_filter :authenticate_user!, :except => :show
	before_filter :composer_validate, :only => [:new, :create]
  before_filter :view_weight, only: [:show, :edit]
  before_filter :load_resources, only: [:new, :create]
	
	def index
		@position = "Мои сборники"
		@albums = current_user.library.albums
	end

	def show
		@album = Album.find(params[:id])
		@title = @album.a_name
		@position = "Просмотр сборника"
    update_statistic(@album)
	end

	def new
		@position = "Создание нового сборника"
	end

	def create
		@album = Album.new(a_name: params[:album][:a_name],
                       composer_id: current_user.id,
                       genre: params[:genre],
                       description: params[:album][:description],
                       author: params[:album][:author],
                       cover: params[:album][:file])
		if @album.save
      redirect_to "/users/composers/#{current_user.id}?type=wait"
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    @position = "Редактирование сборника"
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(params[:album])
      redirect_to action: :edit
    end
  end

  def destroy
    case params[:from]
      when "all"
        @album = Album.find(params[:id])
        @album.delete_from_anywhere
        redirect_to "/users/composers/#{current_user.id}?type=all"
      when "library"
        @album = current_user.library.albums.find(params[:id])
        @album.delete_from_library(current_user.library)
        redirect_to action: :index
      else
        @album = current_user.library.albums.find(params[:id])
        @album.delete_from_library(current_user.library)
        redirect_to action: :index
    end
  end

	def send_to_compilation
		@album = Album.find(params[:id])
		@compilation = Compilation.find(params[:to])
		@compilation.albums << @album
    @compilation.recost
		redirect_to "/users/composers/#{current_user.id}?type=#{params[:send][:where]}"
	end

	def add_compositions
		@album = Album.find(params[:id])
		params[:compositions].each do |id|
	  	@album.compositions << Composition.find(id)
	  end
		@album.recost
		redirect_to "/users/composers/#{current_user.id}?type=#{params[:upload][:where]}"
  end

  protected

    def load_resources
      @inlib = false
    end

    def update_statistic(album)
      if user_signed_in?
        unless current_user.library.albums.where(id: album).exists?
          album.increate_view
        else
          @inlib = true
        end
      end
    end

end

app/controllers/items/compilations_controller.rb
#encoding: utf-8
class Items::CompilationsController < Items::ItemsController
  
before_filter :authenticate_user!, :except => :show
before_filter :composer_validate, :only => [:new, :create]

  def index
  	@position = "Мои коллекции"
  	@compilations = current_user.library.compilations
  end

  def show
  	if user_signed_in?
	    @page_size = "span10"
	    @cover_size = "span3"
	else
	    @page_size = "span12"
	    @cover_size = "span2"
	end
  	@compilation = Compilation.find(params[:id])
  	@position = "Просмотр коллекции"
	@inlib = false
	if user_signed_in?
		if !current_user.library.compilations.where(id: @compilation).exists?
			@compilation.increate_view
		else
			@inlib = true
		end
	end
  end

  def destroy
  	if params[:from].present?
			case params[:from]
				when "all"
					Compilation.find(params[:id]).albums.each do |album|
				  		album.compilation_id = 0
				  		album.save
				  	end
				    compilation = Compilation.find(params[:id])
				  	Compilation.find(params[:id]).delete
				    redirect_to "/users/composers/#{current_user.id}?type=all"
				when "library"
					@compilation = current_user.library.compilations.find(params[:id])
					@compilation.albums.each do |album|
						album.compositions.each do |composition|
							current_user.library.compositions.delete(composition)
						end
						current_user.library.albums.delete(album)
					end
					current_user.library.compilations.delete(@compilation)
					redirect_to action: :index
			end
	else
	  	@compilation = current_user.library.compilations.find(params[:id])
		@compilation.albums.each do |album|
			album.compositions.each do |composition|
				current_user.library.compositions.delete(composition)
			end
			current_user.library.albums.delete(album)
		end
		current_user.library.compilations.delete(@compilation)
		redirect_to action: :index
	end
  end

  def new
  	@position = "Создание новой коллекции"
  	@compilation = Compilation.new
  end

  def create
  	@compilation = Compilation.create(params[:compilation])
  	@compilation.composer_id = current_user.id
  	if @compilation.save
  		redirect_to "/users/composers/#{current_user.id}?type=wait"
  	else
  		render :new
  	end
  end

  def add_albums
  	@compilation = Compilation.find(params[:id])
  	params[:albums].each do |id|
	  	@compilation.albums << Album.find(id)
	end
	cost = 0
	@compilation.albums.each do |a|
		album_cost = 0
		a.compositions.each do |c|
			album_cost += c.cost
		end
		a.update_attributes(cost: album_cost)
		cost += album_cost
	end
	@compilation.update_attributes(cost: cost)
	@compilation.save
	redirect_to "/users/composers/#{current_user.id}?type=#{params[:upload][:where]}"
  end

end

app/controllers/items/compositions_controller.rb
#encoding: utf-8
class Items::CompositionsController < Items::ItemsController

	before_filter :authenticate_user!, only: [:new, :create, :send_to_album]
	before_filter :composer_validate, only: [:new, :create, :send_to_album]

	require 'prawn'

	def index
		@position = "Мои композиции"
		@compositions = current_user.library.compositions
	end

	def show
    @composition = Composition.find(params[:id])
    @title = @composition.c_name
    @position = "Просмотр композиции"
    @inlib = false
    view_weight
    update_statistic(@composition)
	end

	def destroy
    case params[:from]
      when "all"
        @composition = Composition.find(params[:id])
        @composition.delete_from_all
        redirect_to "/users/composers/#{current_user.id}?type=wait"
      when "library"
        @composition = current_user.library.compositions.find(params[:id])
        current_user.library.compositions.delete(@composition)
        redirect_to action: :index
      else
        @composition = current_user.library.compositions.find(params[:id])
        current_user.library.compositions.delete(@composition)
        redirect_to action: :index
    end
	end

	def new 
		@position = "Создание новой композиции"
		@composition = Composition.new
	end

	def create
		if params[:composition][:pdf].present?
      @composition = Composition.new( c_name: params[:composition][:c_name],
                                      composer_id: current_user.id,
                                      genre: params[:genre].blank? ? params[:composition][:genre] : params[:genre],
                                      instrument: params[:instrument],
                                      description: params[:composition][:description],
                                      author: params[:composition][:author],
                                      cover: params[:composition][:file],
                                      #audio: params[:composition][:audio],
                                      cost: params[:cost],
                                      active: false,
                                      album_id: params[:composition][:album_id].blank? ? 0 : params[:composition][:album_id])
      
      @composition.preferences ||= Hash.new
      # Загружаем оригинальный PDF во временную директорию
      ext =  params[:composition][:pdf].original_filename.split('.')[1]
      filename = Guid.new.to_s + "." + ext.to_s
			File.open(TEMP + filename, "wb") {|f| f.write(params[:composition][:pdf].read)}

			# Создание pdf превью
			pdf_processing(@composition,TEMP + filename, 0, PREVIEWS + filename)
			# Конвертация первой страницы pdf в JPG для превью
      count = %x[identify -format %n #{PREVIEWS + filename}]
      preview_name = Guid.new.to_s
      if count.to_i > 1
        Kernel.system "convert -density 75 #{PREVIEWS + filename}[0] #{PREVIEWS + preview_name}.jpg"
        @composition.preferences[:preview] = preview_name + ".jpg"
      else
        @composition.preferences[:preview] = "/assets/no-preview.jpg"
      end
      File.delete(PREVIEWS + filename)

      # Создание печатной версии
      pdf_processing(@composition,TEMP + filename, 1, PDF + filename)
      File.delete(TEMP + filename)
			@composition.preferences[:print] = filename

			# Сохраняем композицию
      if @composition.save
        if params[:composition][:album_id].blank?
          redirect_to "/users/composers/#{current_user.id}?type=wait"
        else
          redirect_to edit_items_album_path(params[:composition][:album_id])
        end
      else
        if params[:composition][:album_id].blank?
          render :new
        else
          redirect_to edit_items_album_path(params[:composition][:album_id])
        end
      end
		else
      if params[:composition][:album_id].blank?
        render :new
      else
        redirect_to edit_items_album_path(params[:composition][:album_id])
      end
		end	
	end



	def send_to_album
		@composition = Composition.find(params[:id])
		@album = Album.find(params[:to])
		@album.compositions << @composition
		@album.recost
		redirect_to "/users/composers/#{current_user.id}?type=#{params[:send][:where]}"
  end


  private

    def update_statistic(composition)
      if user_signed_in?
        unless current_user.library.compositions.where(id: composition).exists?
          composition.increate_view
        else
          @inlib = true
        end
      end
    end






    ##########################################################################
    # КОНВЕРТЕР
    ##########################################################################

    # ОБРАБОТКА PDF
    # Если флаг равен 0 - создаем штамп и расставлем его на всех страницах, 8 раз по 5 штук в строке.
    # Далее ставим копирайты на всех старницах внизу страницы по центру. Создаем белый блок на всю ширину
    # страницы 550px и высотой 30px, ставим его с отступом от нижнего края в 20px и от левого 0, 
    # а сверху него пишем текст.
    #
    # Парметры:
    #   input - файл шаблона, исходный загруженный pdf
    #   flag - тип обработки
    #   output - обработанный файл
    #
    def pdf_processing(composition,input, flag, output)
      if flag == 0
        Prawn::Document.new(:template => input) do 
            	create_stamp("itnotes") do
              		image LOGO, :scale => 0.5
            	end
	            page_count.times do |n|
	              	go_to_page(n + 1)
	              	8.times do |l|
	                	y = l*100
	                	5.times do |m|
	                  		x = (m*100)+40
	                  		transparent(0.3) { stamp_at "itnotes", [x, -y] }
	                	end
	              	end
	            end 
          	render_file output
        end
      else
        template = Prawn::Document.new(template: input) 

        Prawn::Document.new do 
          
          move_down 150

          image BIG_LOGO, scale: 0.6, position: :center

          move_down 200
          font Rails.root.join('public', 'assets',"arial.ttf")
          text "Композиция: #{composition.c_name}", align: :right
          text "Автор: #{composition.author}", align: :right

          move_down 100
          text "Приобретено в магазине ITNotes", align: :center
          text "www.itnot.es", align: :center, valign: :bottom


          template.page_count.times do |n|
            start_new_page(template: input, template_page: n + 1)
          end

          encrypt_document(owner_password: :random,
                          :permissions => { print_document: true,
                                            modify_contents: false,
                                            copy_contents: false,
                                            modify_annotations: false })
          render_file output
        end
      end
    end

end

app/controllers/items/groups_controller.rb
class Items::GroupsController < ApplicationController

	def show
		@group = Group.find(params[:id])
	end
end

app/controllers/items/items_controller.rb
class Items::ItemsController < ApplicationController

	LOGO = Rails.root.join('public', 'assets', 'logo_mini.png')
	BIG_LOGO = Rails.root.join('public', 'assets', 'logo_big.png')
	COVERS = Rails.root.join('public', 'assets', 'covers')
	PREVIEWS = Rails.root.join('public', 'assets', 'previews')
	AUDIO = Rails.root.join('public', 'assets', 'audio')
	PDF = Rails.root.join('public', 'assets', 'pdf')
	TEMP = Rails.root.join('public', 'assets', 'temp')
	
end

app/helpers/items/compilations_helper.rb
module Items::CompilationsHelper
end

app/helpers/items/groups_helper.rb
module Items::GroupsHelper
end

app/helpers/items/items_helper.rb
#encoding: utf-8
module Items::ItemsHelper
  def item_cost(item)
    if item.free?
			content_tag :strong, "бесплатно"
		else
			"Цена: " + item.cost + "$"
    end
  end
end

app/helpers/items/payments_helper.rb
module Items::PaymentsHelper
end

app/views/items/compilations/index.html.haml
= render "layouts/head_bar"
.row-fluid.all-controls
	.span2
		= render "layouts/nav"
	.span10
		.container-fluid.library
			- if !@compilations.any?
				.empty-library
					%h4 У вас нет коллекций.
					%h4 Пора прикупить коллекций в магазине.
			- else
				.section.albums
					.albums-list
						%table.table
							%tbody
								- @compilations.each do |compilation|
									%tr
										%td(rowspan=2)
											%a{href: items_compilation_path(compilation), title: "Просмотреть издание"}
												.compilation-cover-big.thumbnail
													- compilation.albums.limit(4).each do |album|
														= image_tag("/assets/covers/#{album.cover}", size: "75x75")
										%td(colspan=3 rowspan=2)
											%span.name
												= compilation.c_name
											%span.author= compilation.author
											%br
											%span.description= truncate(compilation.description, length: 150)
										%td(rowspan=2 width="70px")
											.tools
												= link_to "", items_compilation_path(compilation), method: :delete, class: "icon-trash",confirm: "Вы уверены, что хотите удалить издание: \"#{compilation.c_name}\" из библиотеки?", title: "Удалить издание"
											

app/views/items/compilations/new.html.haml
= render "layouts/head_bar"
.row-fluid.all-controls
	.span2
		= render "layouts/nav"
	.span10
		= render "layouts/composer_help"
		.uploading
			.row-flid
				.span6
					= form_for :compilation, url: items_compilations_path, html: {class: "validatable-form", id: "compilation"} do |f|
						.control-group
							= f.label 'Название', class: "control-label"
							= f.text_field :c_name
						.control-group
							= f.label 'Описание', class: "control-label"
							= f.text_area :description
						.control-group
							= f.label 'Автор', class: "control-label"
							= f.text_field :author, value: "#{current_user.account.f_name} #{current_user.account.l_name}"
						.control-group
							= f.submit "Создать", class: "btn btn-large btn-success", id: "create-btn", style: "display:none;"
					%a.btn.btn-large#fake-btn-3{href:'#', style: "margin-left:150px; margin-top:-20px;"} Добавить
					.msg
				.span6
					.page-header
						%h3 Подсказки
					%p
						%i.icon-info-sign 
						Все поля обязательны к заполнению!
					%p
						%i.icon-info-sign
						Сборники, которые по вашему мнению должны быть в этой коллекции, вы сможете добавить потом на своей витрине.
					%p
						%i.icon-info-sign
						Обложка для коллекции формируется автоматически, из первых 4 обложек входящих альбомов. Не беспокойтесь по этому поводу.
					%p
						%i.icon-info-sign
						Если в списке инструментов или жанров вы не нашли нужного, то не стесняйтесь и напишите нам какого инструмента не хватает через форму обратной связи. Спасибо!

app/views/items/compilations/show.html.erb
<%= render "layouts/head_bar" %>
<div class= "row-fluid all-controls">
	<%- if user_signed_in? %>
		<div class="span2">
			<%= render "layouts/nav" %>
		</div>
	<% end %>
	<div class="<%= @page_size %>">
		<%- if @inlib == false %>
			<%= render "layouts/search" %>
		<%- end %>	
		<section class="container-fluid album-view">
			<%- if !@compilation.active? %>
				<style>
					.album-view {
						opacity: .6;
					}
				</style>
			<%- end %>
			<div class="section information">
				<div class="page-header">
					<h2><%= @compilation.c_name %></h2>
					<%- if @inlib == true %>
						<span class="marker label label-important">Куплено</span>
					<%- end %>
					<%- if !@compilation.active? %>
						<span class="marker preview label label-important">Предпросмотр</span>
					<%- end %>
				</div>
				<div class="row-fluid">
					<div class="<%= @cover_size %> cover">
						<div class="compilation-cover-big thumbnail">
							<%- @compilation.albums.limit(4).each do |album| %>
								<%= image_tag("/assets/covers/#{album.cover}", size: "75x75")%>
							<%- end %>
						</div>
						<%- if @compilation.active? %>
							<%- if @inlib == true %>
								<%= link_to "Удалить коллекцию", items_compilation_path(@compilation), method: :delete, class: "btn btn-danger btn-mini",confirm: "Вы уверены, что хотите удалить издание: \"#{@compilation.c_name}\" из библиотеки?", title: "Удалить издание" %>
							<%- elsif @compilation.free? %>
								<%- if user_signed_in? %>
									<%= link_to "Добавить в библиотеку", {controller: "payments", action: "create", type: "free", what: "compilation", id: @compilation}, class: "btn btn-success btn-mini", method: :post %>
								<%- else %>
									<a href="#sign_in" class="btn btn-success btn-mini" data-toggle="modal">
										Скачать
									</a>
									Необходима регистрация
								<% end %>
							<%- else %>
								<%- if user_signed_in? %>
									<%= link_to "Купить коллекцию", {controller: "payments", action: "create", type: "paid", what: "compilation", id: @compilation}, class: "btn btn-success btn-mini", method: :post %>
								<%- else %>
									<a href="#sign_in" class="btn btn-success btn-mini" data-toggle="modal">
										Скачать
									</a>
									Необходима регистрация
								<% end %>
							<% end %>
						<% end %>
						<div class="technical">
							<%- if @inlib != true %>
								<div class="cost">
									<%- if @compilation.free? %>
										<strong> бесплатно </strong>
									<%- else %>
										Цена: <%= @compilation.cost %> $
									<%- end %>
								</div>
							<%- end %>
							<div class="date">
								Размещено: <%= @compilation.created_at.to_date.to_s(:db) %>
							</div>
						</div>
					</div>
					<div class="span9 about-album">
						<div class="small-data">
							<span class="composer">Композитор: <%= link_to @compilation.author, show_category_path("Композиторы", @compilation.author ) %> </span>
						</div>
						<h4>Описание</h4>
						<div class="about-album-text"><%= @compilation.description %></div>
					</div>
				</div>
			</div>
			<div class="section compositions">
				<h3>Список сборников</h3>
				<div class="compositions-list">
					<table class="table table-hover">
						<thead>
							<tr>
								<th> # </th>
								<th>Название</th>
								<th>Композитор</th> 
								<th>Композиций</th>
								<%- if @inlib == false %>
									<th>Цена</th>
								<%- end %>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<%- number = 1 %>
							<%- @compilation.albums.each do |album| %>
								<tr>
									<td><%= number %></td>
									<td><%= link_to album.a_name, items_album_path(album), title: "Кликните, чтобы просмотреть альбом." %></td>
									<td><%= link_to album.author, show_category_path("Композиторы", album.author) %></td>
									<td><%= album.compositions.count.to_s %></td>
									<%- if @inlib == false %>
										<td>
											<%- if album.free? %>
												<strong> бесплатно </strong>
											<%- else %> 
												<%= album.cost %> $
											<%- end %>
										</td>
									<%- end %>
								</tr>
								<%- number += 1 %>
							<%- end %>
						</tbody>
					</table>
				</div>
			</div>
		</section>
	</div>
</div>